### ISSUE TITLE
Adding an account through the goal proxy cmd fails

### ISSUE THREAD

**Issue by barnjamin** [algorandfoundation/algokit-cli#102]
```sh
ben@Algo-Guidarelli:~/wiggly$ algokit goal account import
 Couldn't read response: EOF
 Please type your recovery mnemonic below, and hit return when you are done:
Error: Error executing goal; ensure the Sandbox is started by executing `algokit sandbox status
```

A user could still run `algokit sandbox console` and `goal account import` separately to add a new account

**Comment by Loedn** [comment]
reopened #56 to fix this, thanks for raising the issue

**Comment by robdmoore** [comment]
@achidlow I assume what's happening here is that STDIN isn't coming through, make sense to you?

**Comment by robdmoore** [comment]
@barnjamin this should be fixed in `main` and thus in the next algokit release, thanks for reporting
