### ISSUE TITLE
AlgoKit Smart Contract Building Blocks library

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#109]
Acceptance Criteria:

* There will be a GitHub repository that publishes a PyPi package (with automated CI/CD, release notes and versioning)
* There will be a structure where different arcs can be contributed as a Beaker base class, the audit report, any (Markdown) documentation
* The initial set of smart contracts will be determined in the future
* There will be a CONTRIBUTING.md that outlines that all implementations will be audited and will implement a finalised ARC standard, for now it will note that contributions will be from Algorand Foundation only, but if someone wants to email arcs@algorand.foundation.
* Community templates can be managed separately (potentially cloning this repository)

Original notes:

A library for Algorand exists with audited, documented smart contracts and base smart contract templates in PyTEAL that allows Algorand Foundation contributed smart contracts (e.g. ARC reference implementations) and community contributed smart contracts

Inspiration:

* https://github.com/transmissions11/solmate
* https://www.openzeppelin.com/

**Comment by achidlow** [comment]
How will auditing work if these building blocks are open/extendable to user modification(s)?

**Comment by Loedn** [comment]
The initial smart contract will be audited, goes without saying that if they modify it that sc isn't safe anymore
