### ISSUE TITLE
Create community contribution standard across AlgoKit repos

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#11]
We need to decide on a community contribution standard for AlgoKit.

Related: https://allcontributors.org/docs/en/overview

Inspiration:
* https://github.com/algorand/go-algorand/blob/master/CONTRIBUTING.md
* https://github.com/algorand-devrel/beaker/blob/master/CONTRIBUTING.MD

**Comment by abebeos** [comment]
Please note that you need additionally to respond right within the issues, example given here:

- https://github.com/algorandfoundation/algokit-cli/issues/204#issuecomment-1491776713
