### ISSUE TITLE
Error executing algokit after following steps in installation guide

### ISSUE THREAD

**Issue by mdivkovic** [algorandfoundation/algokit-cli#160]
### Environment

Edition	Windows 11 Pro
Version	22H2
Installed on	‎27/‎11/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

Command line: PowerShell

This is a machine that has not been used for development until this very moment.

### Steps to reproduce

Followed Windows installation guide in README verbatim.

### Expected result

Commands listed in installation guide run without errors and need for troubleshooting.

#### Blocker

After performing all the steps in the installation guide without errors, trying to verify the installation via `algokit --version` results in the following output:

`Unhandled ImportError: cannot import name 'git' from 'plumbum.cmd' (C:\Users\Home\.local\pipx\venvs\algokit\Lib\site-packages\plumbum\cmd.py)`

#### Major

- Every `choco install` command had to be run with the additional `-y` argument, otherwise PowerShell just got stuck and would not react to my input at all
- Without manually adding `pip` to path, the command `pip install --user pipx` did not work. Had to run `py -m pip install --user pipx` instead.
- Without manually adding `python` to path, the commands `python -m pipx ensurepath` and `python -m pipx install algokit` did not work. Had to use `py` instead of `python` to invoke the Python Windows Launcher, which doesn't require path modification.

P.S. I'm not a Python dev, though I use it for utility scripts from time to time and have _some_ exposure to the ecosystem and package management. I also do all of my development in the last 5 years on a Mac. Just throwing it out there, in case I missed something stupidly obvious here.

**Comment by daniel-makerx** [comment]
Thanks @mdivkovic for this bug report 🙂. I think the main cause of these issues was some of the recently installed tools would not have been available until your terminal was restarted, I have updated the install instructions to include restarting the terminal when required. Additionally the instructions now include the `-y` argument.

The other issue was that AlgoKit was failing when `git` wasn't available on the path, but this was intended to be an optional dependency so have fixed that. This will be available in the next release.
