### ISSUE TITLE
Improve getting started experience

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#179]
This is a list of updates based on feedback from users thusfar. It's a series of tweaks aimed at making the getting started experience into a good place.

* [x] Getting starting documentation example / page
* [x] CLI -h output pushing them there
* [x] Output from init to the README.md that was output as a next step and replace the link to the template with that unless there isn't one in which case keep the link to the github
* [x] README for beaker template should contain a link to: AlgoKit, Beaker docs, beaker examples, etc.
* [x] It might also make sense to point people from the README to an Algorand intro on the dev portal for people who know basically about Algorand / don’t know the lingo (even words like “dApp” are lingo). --> https://developer.algorand.org/docs/get-started/basics/why_algorand/
* [x] Move the guiding principles of AlgoKit to a separate .md page so the focus is on people there to use the tool
* [x] Explain what AlgoKit is better:
    * AlgoKit is a developer toolkit that is the one-stop shop for developers to build solutions on the [Algorand](https://www.algorand.com/) blockchain, it includes:
        * A **commandline Interface (CLI)** so you can quickly access AlgoKit capabilities
        * A **template library** to get you started faster
        * A set of **framework libraries** so you can build faster
        * A local **isolated Algorand network** so you can simulate real transactions and workloads
* [x] Encourage `algokit bootstrap all` to readme.md in default template rather than just poetry
* [x] Be more explicit about what we mean by "bootstrap"
* [x] Doctor output example should be explicitly noted as an example and not what the output will exactly look like. Be more explicit about when you would run doctor.
* [x] Be explicit about where you can run a given command in the docs and make it clear that init and bootstrap need to be run in a directory you want to do something.
* [x] Resolve both known issues (remove 30k keys, get latest indexer with fix for the other problem per GitHub issue)
* [x] Template selection list should have a description of the template and what it's for and this should also appear in the documentation as a table
* [x] Add "To update AlgoKit" instead of "Update AlgoKit" and "To remove AlgoKit" instead of "Remove AlgoKit" in the installation docs
* [x] In installation docs, after you install it indicate they may need to restart their shell so the path change to AlgoKit takes effect
* [x] Detect if `code` will work before outputting instruction to open using that command
* [x] Add a more explicit statement about what will happen when accepting bootstrapping during init.
* [x] Add output to terminal for `algokit explore` to explain what it's doing and what to expect.
* [x] Some people will read the files in the template (files generated by init) to try to figure out what’s going on. It would be helpful to have those files be self-documenting with comments explaining what the file is for and what the main components of it are - especially for the pyteal files. Do this for the empty file too.
* [x] Explain Poetry and explain we are taking care of virtualenv to remove surprise.
* [x] In the init wizard, some way to show progress through the questions might help ensure we don't lose people. e.g. have a "(step 3/10)"
* [x] The last output line of algokit sandbox start could be "execute 'algokit explore' to explore the local network" or something.
* [x] Warn about, or work around, issues with dappflow + safari
* [x] document `docker cp` usage in `localnet` usage

**Comment by achidlow** [comment]
> In the init wizard, some way to show progress through the questions might help ensure we don't lose people. e.g. have a "(step 3/10)"

Parking this for v1, but we have improved the terminal output a bit

**Comment by robdmoore** [comment]
> Some people will read the files in the template (files generated by init) to try to figure out what’s going on. It would be helpful to have those files be self-documenting with comments explaining what the file is for and what the main components of it are - especially for the pyteal files. Do this for the empty file too.

Did this for the playground template only, if you are using the production template then you probably know what you are doing. This means the playground experience is really nice for new starters.
