### ISSUE TITLE
AlgoKit Pypi util library

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#196]

**Comment by abebeos** [comment]
(please provide more description)

**Comment by abebeos** [comment]
> @[robdmoore](https://github.com/robdmoore) robdmoore closed this as [completed](https://github.com/algorandfoundation/algokit-cli/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [3 hours ago](https://github.com/algorandfoundation/algokit-cli/issues/196#event-9068199275)

@robdmoore , have you overseen my request for more description? above within https://github.com/algorandfoundation/algokit-cli/issues/196#issuecomment-1490814937

What you're doing here is intransparent "solo-development" - how should one follow development without info / references to PRs?

**Comment by robdmoore** [comment]
Sorry, I missed the comment.

This was covering off the initial work that has been completed here: https://github.com/algorandfoundation/algokit-utils-py
