### ISSUE TITLE
Template CI/CD

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#222]
* [x] Add automated version tagging to template on push to main so copier can support resolving versions and remove the can't find tags warning
* [x] Run an automated PR test to check installing via algokit still works

**Comment by daniel-makerx** [comment]
https://github.com/algorandfoundation/algokit-beaker-default-template now has [tests](https://github.com/algorandfoundation/algokit-beaker-default-template/blob/main/tests/test_templates.py) that will output variants of the template based on the various questions into the [tests_generated ](https://github.com/algorandfoundation/algokit-beaker-default-template/tree/main/tests_generated) folder. This allows easily seeing the result of a template change.

Additionally the CI/CD workflow will check these files are up to date to ensure the changes are reviewed.

On push to main a tag and release is automatically done based on conventional commit messages
