### ISSUE TITLE
1.0 release (and post-release docs)

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#223]
* [x] Utils documentation
    * [x] Generated docs for Python
    * [x] Generated docs for TypeScript
    * [x] Handwritten docs for Python
    * [x] Handwritten docs for TypeScript
* [ ] Smart contract development tutorial
* [x] Mental model diagram
* [ ] Creating a template documentation
* [x] 1.0 release of algokit cli
* [x] Final test of everything

**Comment by abebeos** [comment]
I do not understand.

It looks like 1.0.1 is already out:

https://github.com/algorandfoundation/algokit-cli/releases/tag/v1.0.1

What is "1.0 release" about?

**Comment by robdmoore** [comment]
Sorry for the confusion, it’s just shorthand for us to track the remaining things we wanted to do as part of the 1.0 release. The ones that were left we ran out of time for and aren’t essential but we still want to do them so are still tracking it here.

**Comment by abebeos** [comment]
Just change the title to kind of 

`[TODO] Different Tasks`

and it should be clear.

Then possibly add a comment on top

`(different tasks that need to be filed as issues, or done)`
