### ISSUE TITLE
Consider adding "Discussions"

### ISSUE THREAD

**Issue by abebeos** [algorandfoundation/algokit-cli#231]
In order to keep the Issue-Tracker focused on production issues, github discussions could be added.

This would allow:

* visitors to start discussions there (e.g. feature request)
* maintainers to move issues over to discussions

This helps keep the issues focused on short-term production issues.

Candidates for "Discussion" Issues:

- #214 
- #204 
- #53

### Categories

Possibly just a "General" category, maybe additionally a ~"Feature"~"Ideas" one (so visitors can upvote feature requests / Ideas).

**Comment by Loedn** [comment]
Hi @abebeos, thank you for your suggestion, and I think you are correct, will open the discussions section on monday... appreciate the help! (will close once done)

**Comment by daniel-makerx** [comment]
Discussions are now enabled. Closing
