### ISSUE TITLE
Mention optional "Hyper-V" for Docker on Windows

### ISSUE THREAD

**Issue by abebeos** [algorandfoundation/algokit-cli#232]
> Some people have reported problems running WSL 2 on a small proportion of Windows environments (to get the latest Docker experience)
[source](https://github.com/algorandfoundation/algokit-cli/blob/main/docs/architecture-decisions/2022-11-14_sandbox-approach.md#option-1---pre-built-dockerhub-images)

It should be mentioned within the relevant documentation that users can simply switch to Hyper-V if they have problems with WSL2.

---
Personally, after many troubles with WSL2 around 2 years ago(?), I switched back to a Hyper-V backend for Docker. Had nearly never problems again (e.g excessive memory consumptions of WSL2, in some scenarios terribly slow filesystem-access-speed, incompatibilities and strangeness's)

**Comment by robdmoore** [comment]
Can you still run Linux containers using a hyper v backend?

**Comment by abebeos** [comment]
yes.

And having hyper-v, you have always the option to run -independent of docker- a full linux-box including Desktop (though I rarely use this anymore, but it's nice-to-have)

(The most important thing here for algokit is to not give the impression that users must switch from hyper-v to wsl2. this would be an entry-barrier, as the effort is quite high.)

**Comment by joe-p** [comment]
I use hyper-v on Windows for my VMs and just installed Docker + Algokit without a problem. Definitely worth mentioning this in the docs because I'm sure other people also prefer Hyper-V (Windows makes you pick either Hyper-V or WSL enabled, can't have both). One thing to note though is that Hyper-V doesn't seem to be supported on Home licenses of Windows according to the docker docs: https://docs.docker.com/desktop/install/windows-install/

**Comment by abebeos** [comment]
Yeah, it's a "pro only" thing.

Now, I just realized that this was not a end-user documentation, but an design-decision document (guess I hit on that on the end of the workday)

Relevant location in docs:

- https://github.com/algorandfoundation/algokit-cli#install-algokit-on-windows
- https://github.com/algorandfoundation/algokit-cli/blob/main/docs/features/localnet.md#prerequisites

**Comment by robdmoore** [comment]
@daniel-makerx mind updating the docs to reflect this when you get a chance?
