### ISSUE TITLE
Docker Compose not found despite being installed and in PATH

### ISSUE THREAD

**Issue by ismael-elatifi** [algorandfoundation/algokit-cli#235]
```
$ algokit --version
algokit, version 1.0.1

$ algokit localnet start
Error: Docker Compose not found; please install Docker Compose and add to path.
See https://docs.docker.com/compose/install/ for more information.

$ docker-compose --version
docker-compose version 1.25.0, build unknown

$ which docker-compose
/usr/bin/docker-compose

$ echo $PATH | tr ":" "\n" | grep /usr/bin
/usr/bin

$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by abebeos** [comment]
Possible help...

* https://askubuntu.com/questions/1396689/docker-compose-cant-execute-command-docker-compose-not-found
* https://docs.docker.com/desktop/install/ubuntu/

**Comment by robdmoore** [comment]
What’s the output of “algokit doctor”, also, what’s the output of “docker compose version” note the space between “docker” and “compose”?

I think the problem here is you are on an old version of Docker compose. The minimum version we pin to is 2.5. That is a deliberate decision based on the feature set of docker compose at that time and certain bugs that were fixed that would cause unpredictable behaviour.

**Comment by ismael-elatifi** [comment]
I finally managed to reinstall `docker` with `docker compose` (and not `docker-compose`) and I can now run `algokit localnet start` without issue  :)

For others with same issue, I used those 2 resources :  
- https://askubuntu.com/a/1082945/1622259
- https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-install-Docker-and-docker-compose-on-Ubuntu

**Comment by robdmoore** [comment]
Glad to hear you go it working @ismael-elatifi
