### ISSUE TITLE
please delete this issue

### ISSUE THREAD

**Issue by lazaridiscom** [algorandfoundation/algokit-cli#236]

**Comment by robdmoore** [comment]
Hi @lazaridiscom, I completely agree, and we actually do have that in there per https://github.com/algorandfoundation/algokit-cli/blob/main/src/algokit/cli/localnet.py#L38, but the problem in this case is an old version of docker compose before `docker compose` was present falling through the cracks. We did ponder adding that check, but it's such an old version of Docker we didn't look into it at the time. Clearly, there are instances of it out there and the error is confusing enough that it warrants fixing.

I'll leave this issue open to address that particular problem with a clearer error message.
