### ISSUE TITLE
Beaker Module Not Found Error

### ISSUE THREAD

**Issue by kcelestinomaria** [algorandfoundation/algokit-cli#237]
**Problem**

Running algokit demo playground application fails, when Python file is ran, when following docs' instructions here: https://developer.algorand.org/docs/get-started/algokit/

Error, after I run Python File(helloworld.py) in Terminal:
```
algokit-playground/playground/hello_world/helloworld.py
Traceback (most recent call last):
  File "/workspace/algokit-playground/playground/hello_world/helloworld.py", line 2, in <module>
    import beaker
ModuleNotFoundError: No module named 'beaker'

```

```
Running ```algokit doctor``` reproduces this:
algokit doctor
timestamp: 2023-04-02T19:56:35+00:00
AlgoKit: 1.0.1
AlgoKit Python: 3.10.9 (main, Apr  2 2023, 19:41:29) [GCC 9.4.0] (location: /home/.local/pipx/venvs/algokit)
OS: Linux-5.15.0-47-generic-x86_64-with-glibc2.31
docker: 20.10.17
docker compose: 2.17.2
git: 2.37.3
python: 3.10.9 (location: /home/.pyenv/shims/python)
python3: 3.10.9 (location: /home/.pyenv/shims/python3)
pipx: 1.2.0
poetry: 1.3.1
node: 16.19.0
npm: 8.19.3

If you are experiencing a problem with AlgoKit, feel free to submit an issue via:
https://github.com/algorandfoundation/algokit-cli/issues/new
Please include this output, if you want to populate this message in your clipboard, run `algokit doctor -c`
```
Shows pyteal-beaker does not come pre-installed with the current Algokit version, but then even after I run:

```pip install pyteal-beaker```

Problem persists

**Expected**

From docs' walkthrough(https://developer.algorand.org/docs/get-started/algokit/):

```
(playground-py3.11) User@Algo-User-MBP myalgokit project % "/Users/user/code/algokit/myalgokit pro
ject/.venv/bin/python" "/Users/user/code/algokit/myalgokit project/playground/hello_world/demo.py"
Deployed app in txid SBNIJYZUOXVPXDFJHAVDDCO5TQ4WZ7P37QOOQM6CSVSMIURETHNQ
        App ID: 11
        Address: 377KDIVHB7K2LFFJIPUPQFWJGVD36MAP4EI6Y2HAGRAW6JPK4MDUBC3YVY

Hello, Beaker
```

Referenced on Beaker repo as well: https://github.com/algorand-devrel/beaker/issues/228

**Comment by daniel-makerx** [comment]
Hi @kcelestinomaria, the project created by the template relies on a python [virtualenv](https://docs.python.org/3/library/venv.html) that will have all the required dependencies in it. If you are getting `ModuleNotFoundError` then I suspect either the virtualenv has not been created, or not activated. If using VSCode the virtualenv should be activated automatically, however if you are not using VSCode then the virtualenv will need to be activated first.

Firstly, to ensure the virtualenv is created, run `algokit bootstrap all` while in the project root directory (this may have already been done during `algokit init` if you selected Y to the prompt, but running it again won't cause any issues).  This only needs to be done once per project after being created or cloned from a git repo.

Once the venv is present then to activate the environment you can execute `poetry shell` this will start a new shell set up to use the projects virtual python environment. After you have finished you can exit the shell by running `exit`
