### ISSUE TITLE
Fix Copyright Year

### ISSUE THREAD

**Issue by abebeos** [algorandfoundation/algokit-cli#241]
Consider removing the year (saw it in several repos)

Alternatively, update the year:

https://github.com/algorandfoundation/algokit-cli/blob/main/LICENSE#L3

**Comment by robdmoore** [comment]
I don't believe that's necessary. My understanding is you generally only need to include the first year of publish.

https://www.copyrightlaws.com/copyright-symbol-notice-year/ Seems to indicate that's the case too.

**Comment by abebeos** [comment]
@robdmoore , you simply do not close issues that fast, based on an "understanding" that you have.

Maybe reopen, so we can wait for further feedback until this is 100% clear?

**Comment by abebeos** [comment]
To use your resource ( https://www.copyrightlaws.com/copyright-symbol-notice-year/) :

>WHAT ABOUT BLOGS AND WEBSITES?
> New versions or editions of works should contain the publication date of the new version or edition. For constantly evolving websites and blogs that contain works published over several years, the notice may include a range of years (e.g., 2011–2023), starting from the date of the oldest published elements and ending with the date of the newest published elements.

**Comment by abebeos** [comment]
https://softwareengineering.stackexchange.com/questions/210472/is-renewal-of-mit-license-needed-on-github-at-the-beginning-of-each-year

**Comment by robdmoore** [comment]
It's optional to include multiple years, you can just include the first publication date, but there's also no harm in including multiple years so I accepted your suggested change.
