### ISSUE TITLE
TypeScript automated testing support

### ISSUE THREAD

**Issue by robdmoore** [algorandfoundation/algokit-cli#244]
## Acceptance criteria:

* There is an automated testing experience that facilitates reliable, terse tests

## Checklist:

* [x] Implementation
* [x] Documentation

**Comment by abebeos** [comment]
@robdmoore , I assume "**Provide** TypeScript automated testing support".

You mention "Implement", without linking to a PR or explaining.

**Comment by robdmoore** [comment]
https://github.com/algorandfoundation/algokit-utils-ts/blob/main/docs/capabilities/testing.md
