### ISSUE TITLE
algokit-generate (Py&TS): Generators for TS output fail on default args with constant "source"

### ISSUE THREAD

**Issue by JuWeber99** [algorandfoundation/algokit-cli#285]
When using **default arguments** and providing a default value that converts to the ARC-32 application json equivalent of 

```json
{
    "default_arguments": {
        "usdcAssetID": {
            "source": "constant",
            "data": 1 // i used a dummy value here its just an int/bigint
        }
    }
}
```

The error when using the `npm algokit-generator` package indicates to me that the issue may be in the type detection of the **data element** or smth in that direction. Sorry for not digging into your code further but I hope this helps a bit.

**Comment by daniel-makerx** [comment]
Thanks for reporting this @JuWeber99 I can replicate this with TypeScript, but Python seems to work fine. Are you having an issue with both?

**Comment by daniel-makerx** [comment]
This should now be resolved in AlgoKit 1.1.5

**Comment by JuWeber99** [comment]
I try it! To answer your question: i couldnt generate typescript output for both algokit-cli python and npx algokit-client-generator.
I will test it out and let you know!  Thanks in advance for your work

**Comment by JuWeber99** [comment]
works! thank you
