### ISSUE TITLE
UNHANDELED IMPORT ERROR

### ISSUE THREAD

**Issue by JaskaranSingh1255** [algorandfoundation/algokit-cli#299]
C:\Windows\SysWOW64>algokit init
? Select a project template:  playground
     A number of small example applications and demos.
? Name of project / directory to create the project in:  saaf
Starting template copy and render...
Unhandled ImportError: cannot import name '_PathValueError' from 'pydantic.errors' (C:\Users\Manpreet Kaur12\.local\pipx\venvs\algokit\Lib\site-packages\pydantic\errors.py)

C:\Windows\SysWOW64>algokit doctor
timestamp: 2023-07-04T06:39:43+00:00
AlgoKit: 1.1.6
AlgoKit Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] (location: C:\Users\Manpreet Kaur12\.local\pipx\venvs\algokit)
OS: Windows-10-10.0.22621-SP0
docker: 24.0.2
docker compose: 2.19.1
git: 2.41.0.windows.1
python: 3.11.4 (location: C:\Users\Manpreet Kaur12\AppData\Local\Programs\Python\Python311\python.EXE)
python3: 3.9.13 (location: C:\Users\Manpreet Kaur12\AppData\Local\Microsoft\WindowsApps\python3.EXE)
pipx: 1.2.0
poetry: Command not found!
  Poetry is required for some Python-based templates;
  install via `algokit bootstrap` within project directory, or via:
  https://python-poetry.org/docs/#installation
node: 18.16.0
npm: 9.5.1
chocolatey: Command not found!

Please tell me how to correct this error

**Comment by aorumbayev** [comment]
@JaskaranSingh1255 this is fixed on the latest pre release and will be shipped with 1.1.7 fix soon, in the meantime you can do 
```pipx install https://github.com/algorandfoundation/algokit-cli/releases/download/v1.2.0-beta.4/algokit-1.2.0b4-py3-none-any.whl --force``` if you want to install the prerelease version

**Comment by achidlow** [comment]
Fixed by #297, this has been released as 1.2.0 and is available on PyPI now

**Comment by JaskaranSingh1255** [comment]
> pipx install https://github.com/algorandfoundation/algokit-cli/releases/download/v1.2.0-beta.4/algokit-1.2.0b4-py3-none-any.whl --force

It worked thank you so much !!!

**Comment by JaskaranSingh1255** [comment]
> Fixed by #297, this has been released as 1.2.0 and is available on PyPI now

It worked thank you so much !!
