### ISSUE TITLE
Algokit web - please provide installation instructions

### ISSUE THREAD

**Issue by scholtz** [algorandfoundation/algokit-cli#301]
When i go to https://developer.algorand.org/algokit/ there are no installation instructions other than subscribe to email (instructions did not come) or watch the video (quite difficult to copy everything from the video).

Can you make single command that install all dependencies and algokit please? Can you update the web please?

Thank you

**Comment by Loedn** [comment]
`brew install algorandfoundation/tap/algokit` on mac
`choco install algokit` on windows with chocolatey (this is a bit behind because it's moderated there)

We're working on the docs and will soon be included in the dev portal, thanks for raising it

**Comment by scholtz** [comment]
Also i suggest in the section "All set up?" there should be next step.. the link to https://developer.algorand.org/docs/get-started/algokit/

**Comment by aorumbayev** [comment]
also @scholtz  all of the detailed main docs are currently on https://github.com/algorandfoundation/algokit-cli, in the meantime you can refer to the docs on readme and docs folder on the repo itself, the website and hosted docs are going to be included on the main portal once everything is consolidated as @Loedn mentioned.

For algokit utils, client generators, templates and etc detailed docs are also already available on respective repos (its just that they aren't consumable directly from portal just yet)

**Comment by abebeos** [comment]
> soon

So many "soons"

**Comment by Loedn** [comment]
installation instructions are provided here https://developer.algorand.org/docs/get-started/algokit/ thanks for raising it @scholtz
