### ISSUE TITLE
Use official indexer image for localnet 

### ISSUE THREAD

**Issue by Loedn** [algorandfoundation/algokit-cli#355]
v2 indexer is being deprecated and will stop working after the next consensus upgrade.
Need to add conduit and follower node to localnet to support this migration

**Comment by ShoGinn** [comment]
This introduced an error during the `algokit localnet status`

When you added conduit it no longer matches the checks:

https://github.com/algorandfoundation/algokit-cli/blob/450e02ddba02c98d9c8fe8a6baedaf84ef7e9460/src/algokit/cli/localnet.py#L112-L146

My guess is you just have to add conduit
