### ISSUE TITLE
Python 3.12 support for a transitive dependency `multidict`

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-cli#378]
## Description

Certain windows users reported errors during installation via pipx where a transitive dependency fails during build and requires user to have `C++  Build Tools` installed. 

The root cause is the `multidic` dependency that `aiohttp` relies on, cli inherits those by relying on `auth0-python` package.

Dedicated issue on multidict can be tracked here https://github.com/aio-libs/multidict/issues/887.

This issue is to be resolved as soon as a proper support is introduced in the multidict dependency.

**Comment by neilcampbell** [comment]
Hopefully there is a fix for this specific dependency soon.
FYI for anyone reading this, we'll be re-working the install process to remove these kind of transitive dependency issues and make the install experience even more streamlined.
