### ISSUE TITLE
AlgoKit goal is unable to interact with files generated by PyTeal with specific naming conventions

### ISSUE THREAD

**Issue by negar-abbasi** [algorandfoundation/algokit-cli#423]
### Subject of the issue

Reported via [discord](https://discord.com/channels/491256308461207573/1065320801970180168/1208882117912698911), that using the AlgoKit goal to interact with files, it appears that files with multiple dots in their filenames (e.g., contract.approval.teal) are not recognized. For example, while compiling a file named approval.teal using the command AlgoKit goal clerk compile approval.teal works correctly, attempting to compile a file named contract.approval.teal with the command AlgoKit goal clerk compile contract.approval.teal results in an error stating "no such file or directory." This issue affects various commands, including AlgoKit goal app create, making the integration with Python and algokit problematic.

### Steps to reproduce

1. Create a teal file using Puya template with the named `contract.approval.teal`
2. run `algokit goal` command against this file
3. Hit the error message: `contract.approval.teal: open contract.approval.teal: no such file or directory`

**Comment by neilcampbell** [comment]
We are investigating.

**Comment by negar-abbasi** [comment]
This is now fixed in https://github.com/algorandfoundation/algokit-cli/pull/424 and released in version 1.11.4
