### ISSUE TITLE
Unable to update algokit to 2.0

### ISSUE THREAD

**Issue by 1337PaladinS** [algorandfoundation/algokit-cli#466]
While successfully able to update algokit 1.13 -> 2.0 on PC
Unable to do so on Mac, showing the following error (says 1.13 is latest)
<img width="814" alt="image" src="https://github.com/algorandfoundation/algokit-cli/assets/46083510/0f80071c-26ab-4a96-90cf-c4f7005bb182">

**Comment by robdmoore** [comment]
Is this installed via brew? If so you need to `brew upgrade algokit` since pipx isn't in control of the versioning.

**Comment by 1337PaladinS** [comment]
Yes, fixed it!
