### ISSUE TITLE
Issue running `algokit compile python`

### ISSUE THREAD

**Issue by giuliop** [algorandfoundation/algokit-cli#468]
If I run ```algokit compile python file.py``` I get this output:

```
creating virtual environment...
installing puyapy...
Fatal error from pip prevented installation. Full pip output in file:
    /Users/giulio/.local/pipx/logs/cmd_2024-03-30_18.24.30_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.7.0 Requires-Python <4.0,>=3.12; 0.7.1 Requires-Python <4.0,>=3.12; 1.0.0 Requires-Python <4.0,>=3.12; 1.0.1 Requires-Python <4.0,>=3.12
    ERROR: Could not find a version that satisfies the requirement puyapy (from versions: none)
    ERROR: No matching distribution found for puyapy
Error installing puyapy.
```

The file  /Users/giulio/.local/pipx/logs/cmd_2024-03-30_18.24.30_pip_errors.log contains the same error messages as above.

```algokit doctor``` gives this output:

AlgoKit: 2.0.1
AlgoKit Python: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (location: /Users/giulio/.local/pipx/venvs/algokit)
OS: macOS-14.4.1-arm64-arm-64bit
docker: 25.0.3
docker compose: 2.24.5-desktop.1
git: 2.44.0
python: Command not found!
python3: 3.12.2 (location: /opt/homebrew/bin/python3)
pipx: 1.4.3
poetry: 1.8.2
node: 21.7.1
npm: 10.5.0
brew: 4.2.15

I can run `python` without issue from the cli anywhere and I get a Python 3.12.2 interpreter.

I tried both installing algokit with brew and pipx, same result.
The other algokit commands work fine. Using puyapy directly also works fine.

**Comment by robdmoore** [comment]
Yeah, pipx is a bit fickle. If you installed pipx using Python 3.11 (or lower) then it often will use that same interpreter rather than the system one.

`algokit compile py`, if it can't detect `puyapy` in the current project, or globally, will do a `pipx run puyapy` for you, which I suspect is what's failing here.

Can you try what's suggested [here](https://stackoverflow.com/a/77538143) and re-install pipx using a python 3.12 interpreter and then give it another go?

**Comment by giuliop** [comment]
Ok, i made it work, what I did was a bit different since I have python and pipx installed through Homebrew.
With ```brew list``` I noticed that I had both python@3.11 and python@3.12 installed.
I uninstalled 3.11 with ```brew uninstall python@3.11```, reinstalled pipx with Homebrew and now it is working.
Thanks!

**Comment by robdmoore** [comment]
Glad you got it sorted!

**Comment by robdmoore** [comment]
Another option is to install it with pipx manually and tell pipx what version of python to use with something like:

```
pipx install puyapy --python /path/to/python3.12
```
