### ISSUE TITLE
Trouble Getting Algokit to Run in Windows 11

### ISSUE THREAD

**Issue by Jamest145** [algorandfoundation/algokit-cli#469]
Hi All,

I have been spending a few hours trying to get algokit up and running, and I just can't seem to get things working.

I don't know how to get npm installed, and python3 populated according to the algokit doctor:

* timestamp: 2024-03-31T20:58:57+00:00
* AlgoKit: 2.0.1
* AlgoKit Python: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] (location: C:\Users\james\pipx\venvs\algokit)
* OS: Windows-11-10.0.22000-SP0
* docker: 25.0.3
* docker compose: 2.24.6-desktop.1
* git: 2.44.0.windows.1
* python: 3.12.2 (location: C:\Users\james\AppData\Local\Programs\Python\Python312\python.EXE)
* python3: Command not found!
* pipx: 1.5.0
* poetry: 1.8.2
* node: Command not found!
  Node.js is required for some Node.js-based templates;
  install via `algokit project bootstrap` within project directory, or via:
  https://nodejs.dev/en/learn/how-to-install-nodejs/
* npm: Command not found!
* chocolatey: Command not found!

I have been able to run the smart contract hello world, but when I try to get it running in dappflow, I get a network request error:

Network request error. Received status 404 (Not Found): no transaction found for transaction id: XXOAPXUOZWLNSZIYUE6ZDAXN2SJYDN4ADKEERD72IF7LRPZQLWKA

Sorry about the stream of consciousness, but I have been trying to get this running for over four hours and not making much progress. Any pushes in the right direction would be greatly appreciated!

**Comment by robdmoore** [comment]
Suspect the dappflow issue is this: https://github.com/algorandfoundation/algokit-cli/issues/470. So it probably means the transaction executed, but there is a slowdown in indexer and dappflow isn't waiting long enough for the transaction to come back.

Node.js you can install via the url it outputs: https://nodejs.dev/en/learn/how-to-install-nodejs/. You only need it if you want to do a web app or write smart contracts with TypeScript rather than Python.

`python3` not being defined is fine since `python` is, that's only a warning.

**Comment by Jamest145** [comment]
@robdmoore Thank you very much for your response! I'll install Node.js.

As for the transaction error, that is something that is currently an issue, and that will be worked on by the protocol team if I understand correctly.

**Comment by robdmoore** [comment]
It’s not an error that should block you though, it’s just the indexer being slow - everything is working properly without error (rappelled just isn’t handling the slowness well)

**Comment by robdmoore** [comment]
Will close for now since we have a separate ticket to track the indexer problem, but feel free to loop back if you need anything clarified
