### ISSUE TITLE
Latest algod docker images breaks 

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-cli#501]
### Subject of the issue

The latest algod image that localnet uses is causing the latest conduit image to fail to parse the block with the following error: `importer algod.GetBlock() error getting block for round 1, check node configuration: error decoding block for round 1: msgpack decode error [pos 13]: no matching struct field found when decoding stream map with key bi`.

As a result indexer is not advancing, as reported here https://discord.com/channels/491256308461207573/1065320801970180168/1242228411309756489

This can be reproduce by installing AlgoKit CLI version 2.0.4 (`pipx install algokit==2.0.4 --force`) and then running `algokit localnet reset --update`.

Note: Version `2.0.5` has been updated to pin to latest know good algod image, so won't show the issue.

**Comment by neilcampbell** [comment]
Keeping this open to track updates in conduit docker image.

**Comment by joe-p** [comment]
I've made an issue here https://github.com/algorand/conduit/issues/173

**Comment by neilcampbell** [comment]
Thanks @joe-p. I'll close this issue now and keep tabs on the conduit one you've created.
