### ISSUE TITLE
Use native binaries rather than docker

### ISSUE THREAD

**Issue by joe-p** [algorandfoundation/algokit-cli#53]
This has been discussed on a couple of times, but I want to raise the topic again because I think there's an approach we can take that dramatically reduces the friction for the "first-touch" dev experience. 

The main rationale for using docker is because of the postgres DB indexer needs. Having users install Postgres on bare-metal is unreasonable. The indexer, however, is not needed for smart contract development (only full Dapp development). As such, I think it would be reasonable for the default installation of sandnet to not include indexer. Without needing indexer we can then use native binaries. 

The main sticking point with trying to use native binaries is not having Windows binaries. To alleviate this, we could have the Windows version of algokit use WSL when ran on Windows. The requirement for WSL is still not ideal, but it's better than WSL + Docker. 

If a dev wants to eventually use Indexer, there can be an optional flag that creates a docker container on the host network that can communicate with the local algod. Eventually we can hopefully write a Conduit plugin that uses SQLite instead of Postgres and have everything native.

**Comment by joe-p** [comment]
> And it saves much trouble.

While this is true in some contexts, it's not always true. The necessary binaries run on bare metal without any dependencies needed. In the case of Algokit, docker adds more complexity than it removes. If we used native binaries, there wouldn't need to be wrappers around `docker compose` commands and we would not have the UX pains of copying files to/from containers or some of the `ioctl` errors that users run into when working with passwords. Then of course there's the pain of installing docker in the first place (particularly on Windows) and the performance sacrifices (primarily IO on Windows/Mac).

**Comment by abebeos** [comment]
> > And it saves much trouble.
> 
> While this is true in some contexts, it's not always true.
[...] - (not reading through)

I've extracted the essence, and gave my feedback.

It ends here for me.

**Comment by abebeos** [comment]
Seeing the setup effort https://github.com/algorandfoundation/algokit-cli/issues/232#issuecomment-1493427096, and remembering my personal struggle with docker when I first used it (it can take days or weeks to get `fluent` with docker), then "going full native binary without docker" could(!) be a valid goal (valid as in "worth the effort").
