### ISSUE TITLE
Set up Windows Chocolatey installation

### ISSUE THREAD

**Issue by wilsonwaters** [algorandfoundation/algokit-cli#79]
Acceptance Criteria:

* Windows users can `choco install algokit` and get the latest production version of algokit installed to their machine
* If users don't have Python 3.10+ installed then it will be installed for them
* If users don't have pipx installed it will install that for them with pipx available on global path
* New releases are automatically released when a production release of algokit is issued
* Windows users can `choco upgrade algokit` to upgrade to latest available version
* Windows users can `choco uninstall algokit` to remove algokit cli from their system

**Comment by robdmoore** [comment]
After a long moderation wait, looks like Chocolatey package is finally in a workable state: https://community.chocolatey.org/packages/algokit/.
